openapi: 3.2.0
info:
  title: Online Store Gift Certificate Transactions API
  version: '1.0'
  description: Online Store API
servers:
- url: https://www.yoursite.com/api/v1
  description: ''
security:
- X-AC-Auth-Token: []
tags:
- name: Gift Certificate Transactions
paths:
  /gift_certificate_transactions:
    get:
      summary: Get Gift Certificate Transactions
      tags:
      - Gift Certificate Transactions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_count:
                    type: integer
                  gift_certificate_transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/gift_certificate_transactions'
      operationId: get-gift_certificate_transactions
      description: Gets an array of gift certificate transactions.
    post:
      summary: Create a Gift Certificate Transaction
      operationId: post-gift_certificate_transactions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gift_certificate_transactions'
      tags:
      - Gift Certificate Transactions
      description: Creates a gift certificate transactions
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  gift_certificate_id: 28
                  action: SetActive
                  amount: 0
                  is_pre_tax_discount: false
                  order_id: 0
                  order_payment_id: null
                  status: Approved
              properties:
                gift_certificate_id:
                  type: integer
                action:
                  type: string
                amount:
                  type: number
                is_pre_tax_discount:
                  type: boolean
                order_id:
                  type: number
                order_payment_id:
                  type: integer
                status:
                  type: string
            examples:
              Example:
                value:
                  gift_certificate_id: 28
                  action: SetActive
                  amount: 0
                  is_pre_tax_discount: false
                  order_id: 0
                  order_payment_id: null
                  status: Approved
  /gift_certificate_transactions/{id}:
    parameters:
    - schema:
        type: integer
      name: id
      in: path
      required: true
      description: The ID of the `gift_certificate_transactions`
    put:
      summary: Update a Gift Certificate Transaction
      operationId: put-gift_certificate_transactions-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gift_certificate_transactions'
      description: 'Updates a gift certificate transaction. '
      tags:
      - Gift Certificate Transactions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/gift_certificate_transactions'
    delete:
      summary: Delete a Gift Certificate Transaction
      operationId: delete-gift_certificate_transactions-id
      responses:
        '200':
          description: OK
        '404':
          $ref: '#/components/responses/404'
      description: Deletes a gift certificate transaction.
      tags:
      - Gift Certificate Transactions
components:
  responses:
    '404':
      description: Resource Not Found
      content:
        application/json:
          schema:
            description: Not Found
            type: object
            x-examples:
              example-1:
                status_code: 404
                message: Not Found
                details: No resource found
            properties:
              status_code:
                type: number
              message:
                type: string
              details:
                type: string
          examples: {}
      headers: {}
  schemas:
    gift_certificate_transactions:
      type: object
      properties:
        id:
          type: integer
        gift_certificate_id:
          type: integer
        action:
          type: string
        amount:
          type: integer
        is_pre_tax_discount:
          type: boolean
        order_id:
          type: integer
        order_payment_id:
          type: integer
        updated_at:
          type: string
        created_at:
          type: string
        status:
          type: string
  securitySchemes:
    X-AC-Auth-Token:
      name: X-AC-Auth-Token
      type: apiKey
      in: header
