openapi: 3.2.0
info:
  title: Online Store Shipping Rate Adjustments API
  version: '1.0'
  description: Online Store API
servers:
- url: https://www.yoursite.com/api/v1
  description: ''
security:
- X-AC-Auth-Token: []
tags:
- name: Shipping Rate Adjustments
paths:
  /shipping_rate_adjustments:
    get:
      summary: Get Shipping Rate Adjustments
      tags:
      - Shipping Rate Adjustments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_count:
                    type: integer
                  shipping_rate_adjustments:
                    type: array
                    items:
                      $ref: '#/components/schemas/shipping_rate_adjustments'
      operationId: get-shipping_rate_adjustments
      description: Gets an array of shipping rate adjustments.
    post:
      summary: Create a Shipping Rate Adjustment
      operationId: post-shipping_rate_adjustments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/shipping_rate_adjustments'
      description: Creates a shipping rate adjustment.
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  type: Additional Handling
                  amount: 0.0
                  shipping_method_name: UPS Ground
                  shipping_provider: UPS
                  is_unavailable: false
                  product_id: 4
                  available_region_id: 2
                  use_calculated_rate: false
              properties:
                type:
                  type: string
                amount:
                  type: number
                shipping_method_name:
                  type: string
                shipping_provider:
                  type: string
                is_unavailable:
                  type: boolean
                product_id:
                  type: integer
                available_region_id:
                  type: integer
                use_calculated_rate:
                  type: boolean
              required:
              - username
              examples:
                Example:
                  value:
                    type: Additional Handling
                    amount: 0.0
                    shipping_method_name: UPS Ground
                    shipping_provider: UPS
                    is_unavailable: false
                    product_id: 4
                    available_region_id: 2
                    use_calculated_rate: false
      tags:
      - Shipping Rate Adjustments
  /shipping_rate_adjustments/{id}:
    parameters:
    - schema:
        type: integer
      name: id
      in: path
      required: true
      description: The ID of the `shipipng_rate_adjustment`
    put:
      summary: Update a Shipping Rate Adjustment
      operationId: put-shipping_rate_adjustments-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/shipping_rate_adjustments'
      tags:
      - Shipping Rate Adjustments
      description: 'Updates a shipping rate adjustment.


        For more information on shipping rate adjustments, please see our knowledge base: [Shipping Rate Adjustments Overview](https://support.americommerce.com/hc/en-us/articles/223487968-Product-Shipping-Rate-Adjustments).'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/shipping_rate_adjustments'
    delete:
      summary: Delete a Shipping Rate Adjustment
      operationId: delete-shipping_rate_adjustments-id
      responses:
        '200':
          description: OK
        '404':
          $ref: '#/components/responses/404'
      tags:
      - Shipping Rate Adjustments
      description: Deletes a shipping rate adjustment.
components:
  schemas:
    shipping_rate_adjustments:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        amount:
          type: integer
        shipping_method_name:
          type: string
        shipping_provider:
          type: string
        is_unavailable:
          type: boolean
        product_id:
          type: integer
        updated_at:
          type: string
        created_at:
          type: string
        available_region_id:
          type: integer
        use_calculated_rate:
          type: boolean
  responses:
    '404':
      description: Resource Not Found
      content:
        application/json:
          schema:
            description: Not Found
            type: object
            x-examples:
              example-1:
                status_code: 404
                message: Not Found
                details: No resource found
            properties:
              status_code:
                type: number
              message:
                type: string
              details:
                type: string
          examples: {}
      headers: {}
  securitySchemes:
    X-AC-Auth-Token:
      name: X-AC-Auth-Token
      type: apiKey
      in: header
